[General]
# Konfigurasi Utama iwd - AQJ OS

# Izinkan iwd mengelola DNS secara internal
EnableNetworkConfiguration=true

# Opsi resolv.conf (resolvconf / systemd-resolved / none)
NameResolvingService=resolvconf

[Network]
# Aktifkan DHCP client bawaan iwd
EnableIPv6=true

[Scan]
# Interval scan jaringan Wi-Fi (detik)
InitialPeriodicScanInterval=10
MaximumPeriodicScanInterval=300
