# ==============================================================================
# xbps Repository Configuration - AQJ OS
# Ditempatkan di: /etc/xbps.d/00-repository-main.conf
# ==============================================================================

# Repositori Void Linux resmi x86_64 (utama)
repository=https://repo-default.voidlinux.org/current

# Repositori Void Linux untuk nonfree packages (opsional, uncomment jika diperlukan)
# repository=https://repo-default.voidlinux.org/current/nonfree

# Repositori Void Linux multilib (opsional, untuk kompatibilitas 32-bit)
# repository=https://repo-default.voidlinux.org/current/multilib
